### PR TITLE
Remove CleanCSS

### PR DESCRIPTION
**Pull request by lazd**
As far as I can tell, Topdoc has no business minifying CSS and storing it as a property.

Running CleanCSS can cause errors when processing CSS that hasn't yet been processed by PostCSS, and seems unnecessary for documentation generation.

You can see where this is breaking a Topdoc build that is otherwise totally successful here: https://travis-ci.org/adobe/spectrum-css/builds/532900978#L540

### CODE REVIEW

**Comment by lazd** [comment]
Note that [CI is broken](https://travis-ci.org/Topdoc/postcss-topdoc/builds/532908077#L516) and it seems like https://github.com/GarthDB/atomdoc-cli/pull/66 fixes it.

**Comment by GarthDB** [comment]
There are reasons why including the minified css would be helpful in generating docs - we use to generate the css snippet next to the markup in the docs on Topcoat, but since spectrum-css is really the main client, I guess whatever works for spectrum. It will be a breaking change.

**Comment by lazd** [comment]
@GarthDB seems like templates could minify the CSS if they need it... And this was undocumented API, so that means it's not a breaking change :)

**Comment by GarthDB** [comment]
It's not just the minified css - it's the css block corresponding to that doc - the problem is that it doesn't perfectly capture all of the styles that could influence the component.

**Pull request merged**
